spring:
  profiles:
    active: local

  application:
    name: batch-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always


server:
  port: 8010
  shutdown: graceful

---

spring:
  config:
    activate:
      on-profile: main
  application:
    name: fit-group-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://223.130.156.217:3306/batch?validationQuery="select 1"
    username: batch
    password: batch
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    open-in-view: false

  kafka:
    consumer:
      bootstrap-servers: kafka-1:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka-1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  port: 8010
  shutdown: graceful
